version: "3.7"

services:
  smart-meter:
    image: marktermaat/smart-meter-influxdb:latest
    restart: always
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      - LOG_LEVEL=INFO
      - INFLUXDB_DATABASE=my_data
    volumes:
      - ./log:/var/log
